# Generated by Django 2.1.7 on 2019-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190419_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='自我描述'),
        ),
    ]
