# Generated by Django 2.1.7 on 2019-04-19 05:53

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import utils.models_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='名称')),
                ('history', utils.models_field.DictListField(blank=True, unique=False, verbose_name='历史记录')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-created'],
            },
        ),
    ]