# Generated by Django 2.2.4 on 2020-04-30 13:54

from django.db import migrations
import utils.models_field


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='history',
            field=utils.models_field.DictListField(blank=True, null=True, verbose_name='历史记录'),
        ),
    ]
