# Generated by Django 2.1.7 on 2019-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
    ]
