# Generated by Django 2.1.7 on 2019-04-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
