# Generated by Django 2.1.7 on 2019-04-23 09:11

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='verb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='动词'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='unread', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
